// src/lib/infrastructure/prisma-mariadb.ts
// PrismaClient singleton for the vps-next-mariadb profile.
//
// Mirrors prisma.ts but imports PrismaClient from the custom output path
// prisma/mariadb/.prisma/client (generated from prisma/mariadb/schema.prisma).
// This ensures the MariaDB/MySQL client is used rather than the default
// @prisma/client (generated from the postgres schema).
//
// IMPORTANT: This module MUST NOT be imported in Edge runtime code (middleware).
// Prisma Client uses Node.js native modules incompatible with the Edge runtime.
//
// Pre-generation note: The mariadb client (prisma/mariadb/.prisma/client/) is
// generated by postinstall or by running:
//   pnpm prisma generate --schema prisma/mariadb/schema.prisma
// If the generated directory is absent, this module throws MODULE_NOT_FOUND at
// startup — a loud, actionable failure. (Type-checking also requires the
// generated client to exist; postinstall guarantees this after `pnpm install`.)
//
// ## Compile-time drift guard (HIGH fix)
// Types are imported from the GENERATED mariadb client path — NOT asserted as
// `typeof import('@prisma/client')` (the previous cast hid structural drift
// from the compiler entirely). prismaMariadb is exported with its true
// generated type, and the model-level mutual-assignability checks at the
// bottom of this file turn any model/field drift between the two schemas into
// a compile error.
//
// Why model-level (not whole-client) checks: the two generated PrismaClient
// types are NOT mutually assignable even with identical schemas — provider
// surfaces like Prisma.TransactionIsolationLevel ($transaction options)
// legitimately differ between postgresql and mysql. Model row types and
// create-input types are provider-independent, so comparing those captures
// exactly the schema-drift signal without provider noise. The textual guard
// (`pnpm check:schema-drift`, wired into CI) covers the full schema surface.

// eslint-disable-next-line @typescript-eslint/no-require-imports
const { PrismaClient: MariadbPrismaClient } = require('../../../prisma/mariadb/.prisma/client') as typeof import('../../../prisma/mariadb/.prisma/client')

import type {
  PrismaClient as GeneratedMariadbPrismaClient,
  User as MariadbUser,
  Account as MariadbAccount,
  AuditLog as MariadbAuditLog,
} from '../../../prisma/mariadb/.prisma/client'
import type {
  User as PostgresUser,
  Account as PostgresAccount,
  AuditLog as PostgresAuditLog,
} from '@prisma/client'

declare global {
  // eslint-disable-next-line no-var
  var __prismaMariadb__: GeneratedMariadbPrismaClient | undefined
}

function createPrismaMariadbClient(): GeneratedMariadbPrismaClient {
  return new MariadbPrismaClient({
    log:
      process.env.NODE_ENV === 'development'
        ? ['query', 'error', 'warn']
        : ['error'],
  })
}

// In production: always create a fresh client (no module re-evaluation risk).
// In development: reuse the global instance to survive HMR.
export const prismaMariadb: GeneratedMariadbPrismaClient =
  globalThis.__prismaMariadb__ ?? createPrismaMariadbClient()

if (process.env.NODE_ENV !== 'production') {
  globalThis.__prismaMariadb__ = prismaMariadb
}

// ── Compile-time schema drift guards ────────────────────────────────────────
// `MutuallyAssignable<A, B>` collapses to `never` unless A and B are mutually
// assignable, which rejects the `true` literal below and fails `tsc --noEmit`.
// Model ROW types catch field add/remove/rename and scalar-type drift between
// the two schemas. (Create-input types are intentionally NOT compared:
// `id` optionality legitimately differs — the postgres schema uses
// @default(uuid()) while the mariadb schema generates UUIDs in the
// application layer, see prisma/mariadb/schema.prisma header.)
// A second compile-time guard lives in prisma-client.ts: the assignment of
// this client to ProfilePrismaClient (postgres-typed model delegates) is a
// plain type-checked assignment, not a cast.
type MutuallyAssignable<A, B> = [A] extends [B]
  ? [B] extends [A]
    ? true
    : never
  : never

const _userRowDriftGuard: MutuallyAssignable<PostgresUser, MariadbUser> = true
const _accountRowDriftGuard: MutuallyAssignable<PostgresAccount, MariadbAccount> = true
const _auditLogRowDriftGuard: MutuallyAssignable<PostgresAuditLog, MariadbAuditLog> = true

void _userRowDriftGuard
void _accountRowDriftGuard
void _auditLogRowDriftGuard
